using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using highlands.Models.DTO.ReportDTO;

public class ReportDocument : IDocument
{
    private readonly ReportData _data;

    public ReportDocument(ReportData data)
    {
        _data = data;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(30);
            page.Header().Text($"📊 Báo Cáo {_data.ReportType.ToUpper()} ({_data.TimeRangeText})").FontSize(18).Bold();
            page.Content().PaddingVertical(10).Column(col =>
            {
                col.Item().Text($"🧾 Tổng doanh thu: {_data.TotalRevenue:N0} VNĐ").FontSize(14).Bold();

                // Sản phẩm bán chạy
                col.Item().PaddingVertical(10).Text("🔥 Sản phẩm bán chạy:");
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(c => { c.RelativeColumn(); c.ConstantColumn(80); });
                    foreach (var p in _data.BestSellers)
                    {
                        table.Cell().Text(p.Name);
                        table.Cell().Text(p.Quantity.ToString());
                    }
                });

                // Sản phẩm bán ế
                col.Item().PaddingVertical(10).Text("❄️ Sản phẩm bán ế:");
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(c => { c.RelativeColumn(); c.ConstantColumn(80); });
                    foreach (var p in _data.WorstSellers)
                    {
                        table.Cell().Text(p.Name);
                        table.Cell().Text(p.Quantity.ToString());
                    }
                });

                // Doanh thu theo danh mục
                col.Item().PaddingVertical(10).Text("📂 Doanh thu theo danh mục:");
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(c => { c.RelativeColumn(); c.ConstantColumn(100); });
                    foreach (var cat in _data.RevenueByCategory)
                    {
                        table.Cell().Text(cat.Category);
                        table.Cell().Text(cat.Revenue.ToString("N0"));
                    }
                });

                // Doanh thu theo sản phẩm
                col.Item().PaddingVertical(10).Text("📦 Doanh thu theo sản phẩm:");
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(c => { c.RelativeColumn(); c.ConstantColumn(100); });
                    foreach (var p in _data.RevenueByProduct)
                    {
                        table.Cell().Text(p.Name);
                        table.Cell().Text(p.Revenue.ToString("N0"));
                    }
                });

                // Khách hàng thân thiết
                col.Item().PaddingVertical(10).Text("👥 Khách hàng thân thiết:");
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(c => { c.RelativeColumn(); c.ConstantColumn(80); c.ConstantColumn(100); });
                    foreach (var c in _data.TopCustomers)
                    {
                        table.Cell().Text(c.CustomerName);
                        table.Cell().Text($"{c.OrderCount} đơn");
                        table.Cell().Text($"{c.TotalSpent:N0} VNĐ");
                    }
                });

                // Thời gian bán chạy và bán ế
                col.Item().PaddingVertical(10).Text("⏰ Thời gian bán chạy:");
                col.Item().Text($"👉 {_data.PeakTime.TimeRange} ({_data.PeakTime.Revenue:N0} VNĐ)");

                col.Item().Text("🕑 Thời gian bán ế:");
                col.Item().Text($"👉 {_data.OffTime.TimeRange} ({_data.OffTime.Revenue:N0} VNĐ)");

            });

            // Footer
            page.Footer().AlignCenter().Text(x =>
            {
                x.Span("Generated by Highlands System ").FontSize(10);
                x.CurrentPageNumber().FontSize(10);
            });
        });
    }
}
